name: Deploy Synesthesia Demo

on:
  push:
    branches:
      - main

jobs:

  docker-build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    if: ${{ vars.DOCKER_ENABLED == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/synesthesia-demo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/synesthesia-demo:latest
