name: Deploy Synesthesia Demo

on:
  push:
    branches:
      - main

jobs:
  deploy-vercel:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build

      - name: Deploy a Vercel
        run: npx vercel deploy --prod --token=$VERCEL_TOKEN --confirm --scope=$VERCEL_ORG_ID --project=$VERCEL_PROJECT_ID

  docker-build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    if: ${{ vars.DOCKER_ENABLED == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/synesthesia-demo:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/synesthesia-demo:latest
